name: Destroy VPC infra 

on:
  workflow_dispatch:

jobs:
  create-basic-infra:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      #Checkout
      - name: Code Checkout
        uses: actions/checkout@v3

      #AWS CREDENTIALS
      - name: Set up AWS credentials
        run: |
          echo "[default]" >> ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" >> ~/.aws/credentials
          
      #Terraform execution
      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run:  terraform destroy -auto-approve