name: Destroy VPC infra 

on:
  workflow_dispatch:

jobs:
  create-basic-infra:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      #Checkout
      - name: Code Checkout
        uses: actions/checkout@v3

      #AWS CREDENTIALS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }} # Replace with your AWS region
          role-to-assume: ${{ secrets.AWS_ROLE }} # Replace with the ARN of the role to assume
          
      #Terraform execution
      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run:  terraform destroy -auto-approve